name: Debug App Content

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      # Debug repository contents
      - name: List Repository Files
        run: |
          echo "Repository Contents:"
          ls -R

      # Clean Derived Data to avoid stale builds
      - name: Clean Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      # Clean and Build
      - name: Clean and Build Project
        run: |
          xcodebuild clean \
            -project "controller-deadzone-main/Controller Deadzone.xcodeproj" \
            -scheme "Controller Deadzone"

      # Archive Project
      - name: Archive Project
        run: |
          xcodebuild -project "controller-deadzone-main/Controller Deadzone.xcodeproj" \
            -scheme "Controller Deadzone" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/ControllerDeadzone.xcarchive \
            CODE_SIGNING_ALLOWED=NO archive

      # Debug archive contents
      - name: List Archive Files
        run: |
          echo "Contents of the .xcarchive:"
          ls -R $PWD/build/ControllerDeadzone.xcarchive

      # Debug app contents
      - name: List App Files
        run: |
          echo "Contents of the .app bundle:"
          ls -R $PWD/build/ControllerDeadzone.xcarchive/Products/Applications/Controller\ Deadzone.app

      # Package App into .ipa
      - name: Create .ipa File
        run: |
          rm -rf Payload/
          mkdir -p Payload
          cp -R "$PWD/build/ControllerDeadzone.xcarchive/Products/Applications/Controller Deadzone.app" Payload/
          zip -r ControllerDeadzone.ipa Payload
          mv ControllerDeadzone.ipa $PWD/build/

      # Upload .ipa as artifact
      - name: Upload Unsigned IPA
        uses: actions/upload-artifact@v3
        with:
          name: Unsigned-iPA
          path: build/*.ipa
