name: Build Unsigned IPA

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Xcode
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      # Create exportOptions.plist
      - name: Create exportOptions.plist
        run: |
          cat <<EOF > exportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>compileBitcode</key>
              <false/>
              <key>thinning</key>
              <string>&lt;none&gt;</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>teamID</key>
              <string>XXXXXXXXXX</string> <!-- Replace with your actual Team ID -->
              <key>provisioningProfiles</key>
              <dict>
                <key>com.mfsaglam.Controller-Deadzone</key> <!-- Replace with your app's bundle identifier -->
                <string>XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX</string> <!-- Replace with your provisioning profile ID -->
              </dict>
          </dict>
          </plist>
          EOF

      # Build the unsigned IPA
      - name: Build Unsigned IPA
        run: |
          # Create an output directory for the IPA
          mkdir -p build/unsigned-ipa

          # Build the archive with no code signing and skip signing entirely
          xcodebuild -project "controller-deadzone-main/Controller Deadzone.xcodeproj" \
            -scheme "Controller Deadzone" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/ControllerDeadzone.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            DEVELOPMENT_TEAM="XXXXXXXXXX" \  # Replace with actual Team ID
            PROVISIONING_PROFILE_SPECIFIER="" \
            clean archive

          # Export the IPA with no code signing, no team required
          xcodebuild -exportArchive \
            -archivePath build/ControllerDeadzone.xcarchive \
            -exportPath build/unsigned-ipa \
            -exportOptionsPlist exportOptions.plist \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            DEVELOPMENT_TEAM="XXXXXXXXXX" \  # Replace with actual Team ID
            PROVISIONING_PROFILE_SPECIFIER="" \
            -allowProvisioningUpdates

      # Upload the IPA as an artifact
      - name: Upload Unsigned IPA
        uses: actions/upload-artifact@v3
        with:
          name: unsigned-ipa
          path: build/unsigned-ipa/
