name: Build Unsigned iOS .ipa

on:
  workflow_dispatch:  # Triggered manually via GitHub UI

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the repository with full history and submodules
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      # Debug repository contents to ensure all files are present
      - name: Debug Repository Contents
        run: |
          ls -R  # List all files in the repo to verify the structure

      # Install CocoaPods (if applicable)
      - name: Install CocoaPods
        run: |
          pod install --repo-update || echo "No CocoaPods dependencies"  # Install dependencies if any

      # Clean Derived Data to avoid stale builds
      - name: Clean Derived Data
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData  # Ensure a clean build by removing old derived data

      # Clean the project build
      - name: Clean Build
        run: |
          xcodebuild clean \
            -project "controller-deadzone-main/Controller Deadzone.xcodeproj" \
            -scheme "Controller Deadzone"  # Clean any previous build artifacts

      # Archive the project
      - name: Archive Project
        run: |
          xcodebuild -project "controller-deadzone-main/Controller Deadzone.xcodeproj" \
            -scheme "Controller Deadzone" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/ControllerDeadzone.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" archive  # Archive the project with no code signing

      # Debug the contents of the archive to ensure it was created successfully
      - name: Debug Archive Contents
        run: |
          ls -R $PWD/build/ControllerDeadzone.xcarchive  # List the contents of the archive to ensure it's correct

      # Prepare the IPA for export
      - name: Export .ipa
        run: |
          rm -rf Payload/
          mkdir -p Payload
          cp -R "$PWD/build/ControllerDeadzone.xcarchive/Products/Applications/Controller Deadzone.app" Payload/
          ls -R Payload/  # Debug the Payload folder structure
          zip -r ControllerDeadzone.ipa Payload  # Create the IPA from the Payload directory
          mv ControllerDeadzone.ipa $PWD/build/  # Move the IPA to the build folder

      # Upload the unsigned IPA as an artifact
      - name: Upload Unsigned IPA
        uses: actions/upload-artifact@v3
        with:
          name: Unsigned-iPA
          path: build/*.ipa  # Upload the IPA to GitHub as an artifact
